apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: deployment
metadata: 
  labels:
    name: springboot
  name: springboot-deployment 
spec: 
  replicas: 1
  template:
    metadata:
      labels:
       name: springboot
    spec: 
      containers: 
      - name: springboot 
        image: 4544544/spring-boot-mongo:latest
        imagePullPolicy: Always
        ports: 
        - name: springboot 
          containerPort: 8080
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  labels:
    name: springboot
  name: springboot-service 
spec: 
  selector: 
    name: springboot 
  ports: 
  - protocol: TCP 
    port: 8080 
    targetPort: 8080 
  type: NodePort
---

apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2 mongodb
kind: deployment 
metadata: 
  labels:
    name: mongo
  name: mongo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 2707
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath: 
           path: /tmp/dbbackup
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata:
  labels:
    name: mongo
  name: mongo-service
spec:
  type: ClusterIP 
  ports: 
  - protocol: TCP 
    port: 27017 
    targetPort: 27017 
  selector:
      name: mongo
